title: Asteroides
description: Repositorio para curvas de luz e información de asteroides obtenidos en la cámara Schmidt
baseurl: "https://asteroidesinaoe.github.io"

username: Asteroides
typing_text: Base de datos
email: INAOERep@outlook.com
github_username: AsteroidesINAOE
twitter_username: inaoe_mx

show_aboutme_card: true
# about_me_title: The will be displayed as the title in the About Me section
about_me_title: Asteroides
# about_me_description: This will be displayed under the title.
about_me_description:

show_aboutme_card: true
# about_me_title: The will be displayed as the title in the About Me section
about_me_title: Asteroides
# about_me_description: This will be displayed under the title.
about_me_description:

# CONTACT SECTION
show_contact_card: true
contact_title: Contacto
contact_description: 

# GITHUB-METADATA
# Set this to your forked repository
# > e.g. <user>/<user>.github.io
repository: AsteroidesINAOE/AsteroidesINAOE.github.io

projects:
  # sortby:
  # > set this to pushed, if you want to sort your github repositories by time.
  # > set this to stars, if you want to sort your github repositories by stars.
  sort_by: pushed
  exclude:
    # archived:
    # > setting this to true, will exclude archived repositories
    # > setting this to false, will also display archived repositories
    archived: true
    # forks:
    # > setting this to true, will exclude forked repositories
    # > setting this to false, will also display forked repositories
    forks: true
    # projects: A list of the repository names you want to exclude from the listing.
    projects:
    # - repo1-to-be-excluded
    # - repo2-to-be-excluded

# GOOGLE-ANALYTICS
# Set the id, if you want to track your website with Google Analytics
# > set this to "", if you do not want to track with Google Analytics
google-analytics:
  id: ""
### END OF VALUES YOU SHOULD CHANGE ###

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
